#!/bin/bash

#
# inter flash
#
python dlhadd.py mcc8v4_cocktail_p00 test11_flash flash_ana 1> log/cocktail_p00_test11_flash_ana.log 2> err/cocktail_p00_test11_flash_ana.err
python dlhadd.py mcc8v4_cocktail_p01 test11_flash flash_ana 1> log/cocktail_p01_test11_flash_ana.log 2> err/cocktail_p01_test11_flash_ana.err
python dlhadd.py mcc8v4_cocktail_p02 test11_flash flash_ana 1> log/cocktail_p02_test11_flash_ana.log 2> err/cocktail_p02_test11_flash_ana.err
python dlhadd.py mcc8v4_cocktail_p03 test11_flash flash_ana 1> log/cocktail_p03_test11_flash_ana.log 2> err/cocktail_p03_test11_flash_ana.err
python dlhadd.py mcc8v4_cocktail_p04 test11_flash flash_ana 1> log/cocktail_p04_test11_flash_ana.log 2> err/cocktail_p04_test11_flash_ana.err

python dlhadd.py mcc8v6_bnb5e19 test11_flash flash_ana 1> log/bnb5e19_test11_flash_ana.log 2> err/bnb5e19_test11_flash_ana.err
python dlhadd.py mcc8v6_extbnb test11_flash flash_ana 1> log/extbnb_test11_flash_ana.log 2> err/extbnb_test11_flash_ana.err
python dlhadd.py overlay_bnbcosmic_full test11_flash flash_ana 1> log/overlay_test11_flash_ana.log 2> err/overlay_test11_flash_ana.err


#
# inter cosmic
#
python dlhadd.py mcc8v4_cocktail_p00 test11_cosmic cosmic_ana 1> log/cocktail_p00_test11_cosmic_ana.log 2> err/cocktail_p00_test11_cosmic_ana.err
python dlhadd.py mcc8v4_cocktail_p01 test11_cosmic cosmic_ana 1> log/cocktail_p01_test11_cosmic_ana.log 2> err/cocktail_p01_test11_cosmic_ana.err
python dlhadd.py mcc8v4_cocktail_p02 test11_cosmic cosmic_ana 1> log/cocktail_p02_test11_cosmic_ana.log 2> err/cocktail_p02_test11_cosmic_ana.err
python dlhadd.py mcc8v4_cocktail_p03 test11_cosmic cosmic_ana 1> log/cocktail_p03_test11_cosmic_ana.log 2> err/cocktail_p03_test11_cosmic_ana.err
python dlhadd.py mcc8v4_cocktail_p04 test11_cosmic cosmic_ana 1> log/cocktail_p04_test11_cosmic_ana.log 2> err/cocktail_p04_test11_cosmic_ana.err

python dlhadd.py mcc8v6_bnb5e19 test11_cosmic cosmic_ana 1> log/bnb5e19_test11_cosmic_ana.log 2> err/bnb5e19_test11_cosmic_ana.err
python dlhadd.py mcc8v6_extbnb test11_cosmic cosmic_ana 1> log/extbnb_test11_cosmic_ana.log 2> err/extbnb_test11_cosmic_ana.err
python dlhadd.py overlay_bnbcosmic_full test11_cosmic cosmic_ana 1> log/overlay_test11_cosmic_ana.log 2> err/overlay_test11_cosmic_ana.err