#!/bin/bash

#
# dllee_analysis
#

# python dlhadd.py mcc8v4_cocktail_p00 test11 dllee_analysis 1> log/cocktail_p00_test11_dllee_analysis.log 2> log/cocktail_p00_test11_dllee_analysis.err
# python dlhadd.py mcc8v4_cocktail_p01 test11 dllee_analysis 1> log/cocktail_p01_test11_dllee_analysis.log 2> log/cocktail_p01_test11_dllee_analysis.err
# python dlhadd.py mcc8v4_cocktail_p02 test11 dllee_analysis 1> log/cocktail_p02_test11_dllee_analysis.log 2> log/cocktail_p02_test11_dllee_analysis.err
# python dlhadd.py mcc8v4_cocktail_p03 test11 dllee_analysis 1> log/cocktail_p03_test11_dllee_analysis.log 2> log/cocktail_p03_test11_dllee_analysis.err
# python dlhadd.py mcc8v4_cocktail_p04 test11 dllee_analysis 1> log/cocktail_p04_test11_dllee_analysis.log 2> log/cocktail_p04_test11_dllee_analysis.err

# python dlhadd.py mcc8v6_bnb5e19 test11 dllee_analysis 1> log/bnb5e19_test11_dllee_analysis.log 2> log/bnb5e19_test11_dllee_analysis.err
# python dlhadd.py mcc8v6_extbnb test11 dllee_analysis 1> log/extbnb_test11_dllee_analysis.log 2> log/extbnb_test11_dllee_analysis.err
python dlhadd.py overlay_bnbcosmic_full test11 dllee_analysis 1> log/overlay_bnbcosmic_full_dllee_analysis.log 2> log/overlay_bnbcosmic_full_dllee_analysis.log

#
# dllee_vertex
#

# python dlhadd.py mcc8v4_cocktail_p00 test11 dllee_vertex 1> log/cocktail_p00_test11_dllee_vertex.log 2> log/cocktail_p00_test11_dllee_vertex.err
# python dlhadd.py mcc8v4_cocktail_p01 test11 dllee_vertex 1> log/cocktail_p01_test11_dllee_vertex.log 2> log/cocktail_p01_test11_dllee_vertex.err
# python dlhadd.py mcc8v4_cocktail_p02 test11 dllee_vertex 1> log/cocktail_p02_test11_dllee_vertex.log 2> log/cocktail_p02_test11_dllee_vertex.err
# python dlhadd.py mcc8v4_cocktail_p03 test11 dllee_vertex 1> log/cocktail_p03_test11_dllee_vertex.log 2> log/cocktail_p03_test11_dllee_vertex.err
# python dlhadd.py mcc8v4_cocktail_p04 test11 dllee_vertex 1> log/cocktail_p04_test11_dllee_vertex.log 2> log/cocktail_p04_test11_dllee_vertex.err

# python dlhadd.py mcc8v6_bnb5e19 test11 dllee_vertex 1> log/bnb5e19_test11_dllee_vertex.log 2> log/bnb5e19_test11_dllee_vertex.err
# python dlhadd.py mcc8v6_extbnb test11 dllee_vertex 1> log/extbnb_test11_dllee_vertex.log 2> log/extbnb_test11_dllee_vertex.err
python dlhadd.py overlay_bnbcosmic_full test11 dllee_vertex 1> log/overlay_bnbcosmic_full_dllee_vertex.log 2> log/overlay_bnbcosmic_full_dllee_vertex.log


#
# FinalVertexVariables
#

# python dlhadd.py mcc8v4_cocktail_p00 test11 FinalVertexVariables 1> log/cocktail_p00_test11_FinalVertexVariables.log 2> log/cocktail_p00_test11_FinalVertexVariables.err
# python dlhadd.py mcc8v4_cocktail_p01 test11 FinalVertexVariables 1> log/cocktail_p01_test11_FinalVertexVariables.log 2> log/cocktail_p01_test11_FinalVertexVariables.err
# python dlhadd.py mcc8v4_cocktail_p02 test11 FinalVertexVariables 1> log/cocktail_p02_test11_FinalVertexVariables.log 2> log/cocktail_p02_test11_FinalVertexVariables.err
# python dlhadd.py mcc8v4_cocktail_p03 test11 FinalVertexVariables 1> log/cocktail_p03_test11_FinalVertexVariables.log 2> log/cocktail_p03_test11_FinalVertexVariables.err
# python dlhadd.py mcc8v4_cocktail_p04 test11 FinalVertexVariables 1> log/cocktail_p04_test11_FinalVertexVariables.log 2> log/cocktail_p04_test11_FinalVertexVariables.err

# python dlhadd.py mcc8v6_bnb5e19 test11 FinalVertexVariables 1> log/bnb5e19_test11_FinalVertexVariables.log 2> log/bnb5e19_test11_FinalVertexVariables.err
# python dlhadd.py mcc8v6_extbnb test11 FinalVertexVariables 1> log/extbnb_test11_FinalVertexVariables.log 2> log/extbnb_test11_FinalVertexVariables.err
python dlhadd.py overlay_bnbcosmic_full test11 FinalVertexVariables 1> log/overlay_bnbcosmic_full_FinalVertexVariables.log 2> log/overlay_bnbcosmic_full_FinalVertexVariables.log

